"Filed out from Dolphin Smalltalk"!

CefReferenceCountedObject subclass: #CefPreferencesRegistrar
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
CefPreferencesRegistrar guid: (GUID fromString: '{7895e6e5-4e51-41ca-bc69-dc75e6b6ebfd}')!
CefPreferencesRegistrar comment: ''!
!CefPreferencesRegistrar categoriesForClass!External-Data-Structured! !
