"Filed out from Dolphin Smalltalk"!

CefEventHandler subclass: #CefRequestContextHandler
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

CefRequestContextHandler guid: (GUID fromString: '{16f2386c-38d6-489a-8edb-d15632082921}')!

CefRequestContextHandler comment: ''!

!CefRequestContextHandler categoriesForClass!External-Data-Structured! !

