"Filed out from Dolphin Smalltalk"!

CefEventHandler subclass: #CefResourceBundleHandler
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

CefResourceBundleHandler guid: (GUID fromString: '{321f01af-1b29-49c5-b8f9-96c32f3860ac}')!

CefResourceBundleHandler comment: ''!

!CefResourceBundleHandler categoriesForClass!External-Data-Structured! !

