"Filed out from Dolphin Smalltalk"!

RuntimeSessionManager subclass: #CefSessionManager
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
CefSessionManager guid: (GUID fromString: '{5096440b-cd2a-4608-902d-3946a4474237}')!
CefSessionManager comment: ''!
!CefSessionManager categoriesForClass!Unclassified! !
!CefSessionManager methodsFor!

main
	CefSubprocessRunner new runMainProcess! !
!CefSessionManager categoriesForMethods!
main!public! !
!

