"Filed out from Dolphin Smalltalk"!

Object subclass: #CefNavigationEvent
	instanceVariableNames: 'destination formData hashChange navigationType userInitiated'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

CefNavigationEvent guid: (GUID fromString: '{a72779ba-ca57-4ad8-9e7a-7cdbab436546}')!

CefNavigationEvent comment: ''!

!CefNavigationEvent categoriesForClass!Kernel-Objects! !

!CefNavigationEvent methodsFor!

destination
	^destination!

destination: anObject
	destination := anObject!

formData
	^formData!

formData: anObject
	formData := anObject!

hashChange
	^hashChange!

hashChange: anObject
	hashChange := anObject!

navigationType
	^navigationType!

navigationType: anObject
	navigationType := anObject!

userInitiated
	^userInitiated!

userInitiated: anObject
	userInitiated := anObject! !

!CefNavigationEvent categoriesForMethods!
destination!accessing!private! !
destination:!accessing!private! !
formData!accessing!private! !
formData:!accessing!private! !
hashChange!accessing!private! !
hashChange:!accessing!private! !
navigationType!accessing!private! !
navigationType:!accessing!private! !
userInitiated!accessing!private! !
userInitiated:!accessing!private! !
!

