"Filed out from Dolphin Smalltalk"!

Object subclass: #BrowserObject
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!

BrowserObject guid: (GUID fromString: '{a14f25a0-6d55-46db-b99a-0d836d7c7a72}')!

BrowserObject comment: ''!

!BrowserObject categoriesForClass!Kernel-Objects! !

!BrowserObject class methodsFor!

new
	^super new initialize! !

!BrowserObject class categoriesForMethods!
new!public! !
!

