"Filed out from Dolphin Smalltalk"!

Smalltalk at: #ChromiumConstants put: (PoolConstantsDictionary named: #ChromiumConstants)!
ChromiumConstants at: 'SESSION_COMMAND_ADD_TAB_EXTRA_DATA' put: 16r21!
ChromiumConstants at: 'SESSION_COMMAND_ADD_WINDOW_EXTRA_DATA' put: 16r22!
ChromiumConstants at: 'SESSION_COMMAND_LAST_ACTIVE_TIME' put: 16r15!
ChromiumConstants at: 'SESSION_COMMAND_NAVIGATION_PATH_PRUNED_FROM_BACK' put: 16r5!
ChromiumConstants at: 'SESSION_COMMAND_SESSION_STORAGE_ASSOCIATED' put: 16r13!
ChromiumConstants at: 'SESSION_COMMAND_SET_ACTIVE_WINDOW' put: 16r14!
ChromiumConstants at: 'SESSION_COMMAND_SET_EXTENSION_APP_ID' put: 16rD!
ChromiumConstants at: 'SESSION_COMMAND_SET_PINNED_STATE' put: 16rC!
ChromiumConstants at: 'SESSION_COMMAND_SET_SELECTED_NAVIGATION_INDEX' put: 16r7!
ChromiumConstants at: 'SESSION_COMMAND_SET_SELECTED_TAB_IN_INDEX' put: 16r8!
ChromiumConstants at: 'SESSION_COMMAND_SET_TAB_DATA' put: 16r1E!
ChromiumConstants at: 'SESSION_COMMAND_SET_TAB_GROUP' put: 16r19!
ChromiumConstants at: 'SESSION_COMMAND_SET_TAB_GROUP_METADATA_2' put: 16r1B!
ChromiumConstants at: 'SESSION_COMMAND_SET_TAB_GUID' put: 16r1C!
ChromiumConstants at: 'SESSION_COMMAND_SET_TAB_INDEX_IN_WINDOW' put: 16r2!
ChromiumConstants at: 'SESSION_COMMAND_SET_TAB_USER_AGENT_OVERRIDE' put: 16r12!
ChromiumConstants at: 'SESSION_COMMAND_SET_TAB_USER_AGENT_OVERRIDE_2' put: 16r1D!
ChromiumConstants at: 'SESSION_COMMAND_SET_TAB_WINDOW' put: 16r0!
ChromiumConstants at: 'SESSION_COMMAND_SET_WINDOW_APP_NAME' put: 16rF!
ChromiumConstants at: 'SESSION_COMMAND_SET_WINDOW_BOUNDS' put: 16r1!
ChromiumConstants at: 'SESSION_COMMAND_SET_WINDOW_BOUNDS_2' put: 16rA!
ChromiumConstants at: 'SESSION_COMMAND_SET_WINDOW_BOUNDS_3' put: 16rE!
ChromiumConstants at: 'SESSION_COMMAND_SET_WINDOW_TYPE' put: 16r9!
ChromiumConstants at: 'SESSION_COMMAND_SET_WINDOW_USER_TITLE' put: 16r1F!
ChromiumConstants at: 'SESSION_COMMAND_SET_WINDOW_VISIBLE_ON_ALL_WORKSPACES' put: 16r20!
ChromiumConstants at: 'SESSION_COMMAND_SET_WINDOW_WORKSPACE_2' put: 16r17!
ChromiumConstants at: 'SESSION_COMMAND_STORAGE_BACKEND' put: 16rFF!
ChromiumConstants at: 'SESSION_COMMAND_TAB_CLOSED' put: 16r10!
ChromiumConstants at: 'SESSION_COMMAND_TAB_NAVIGATION_PATH_PRUNED' put: 16r18!
ChromiumConstants at: 'SESSION_COMMAND_TAB_NAVIGATION_PRUNED_FROM_FRONT' put: 16rB!
ChromiumConstants at: 'SESSION_COMMAND_UPDATE_TAB_NAVIGATION' put: 16r6!
ChromiumConstants at: 'SESSION_COMMAND_WINDOW_CLOSED' put: 16r11!
ChromiumConstants at: 'TAB_COMMAND_SELECT_NAVIGATION_IN_TAB' put: 16r4!
ChromiumConstants at: 'TAB_COMMAND_UPDATE_TAB_NAVIGATION' put: 16r1!
ChromiumConstants shrink!
